name: integration

on:
  push:
    branches:
      - v2
  schedule:
    # every day at 02:00 UTC
    - cron: '0 2 * * *'

jobs:
  integration:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          path: infoblox.bloxone

      - name: Set up integration_config.yml
        run: |
          echo "api_key: ${{ secrets.BLOXONE_API_KEY }}" > infoblox.bloxone/tests/integration/integration_config.yml
          echo "csp_url: ${{ secrets.BLOXONE_CSP_URL }}" >> infoblox.bloxone/tests/integration/integration_config.yml

      - uses: ansible-community/ansible-test-gh-action@v1.15.0
        with:
          collection-src-directory: infoblox.bloxone
          ansible-core-version: 'stable-2.15'
          target-python-version: '3.11'
          testing-type: integration
